@echo off
:: ========================================

:: find configs dir (current script dir)
for /f "delims=" %%i in ("%~dp0") do (
  set "MY_CONFIGS=%%~fi"
)
:: remove trailing '\' from %MY_CONFIGS%
if "%MY_CONFIGS:~-1%" == "\" set "MY_CONFIGS=%MY_CONFIGS:~0,-1%"

:: find root dir (parent of configs dir)
for /f "delims=" %%i in ("%MY_CONFIGS%\..") do (
  set "MY_ROOT=%%~fi"
)

:: config alacritty
:: ========================================

:: create alacritty directory
if not exist "%APPDATA%\alacritty" (
  mkdir "%APPDATA%\alacritty"
)

set "MY_CONFIGS_ESCAPED=%MY_CONFIGS:\=\\%"
set "MY_ROOT_ESCAPED=%MY_ROOT:\=\\%"

:: generate alacritty.toml
(
echo # this file is auto-generated by github.com/jwu/configs
echo [general]
echo import = ["%MY_CONFIGS_ESCAPED%\\alacritty.toml"]
echo.
echo [terminal]
echo [terminal.shell]
echo program = "cmd.exe"
echo args = ["/s", "/k", "%MY_CONFIGS_ESCAPED%\\init.bat"]
) > %APPDATA%\alacritty\alacritty.toml

:: config eza
:: ========================================

:: create eza directory
if not exist "%USERPROFILE%\.config" (
  mkdir "%USERPROFILE%\.config"
)
if not exist "%USERPROFILE%\.config\eza" (
  mkdir "%USERPROFILE%\.config\eza"
)

:: config neovim
:: ========================================

:: create nvim directory
if not exist "%LOCALAPPDATA%\nvim" (
  mkdir "%LOCALAPPDATA%\nvim"
)

:: generate init.lua
(
echo -- this file is auto-generated by github.com/jwu/configs
echo dofile^("%MY_ROOT_ESCAPED%\\common\\.config\\nvim\\init.lua"^)
) > "%LOCALAPPDATA%\nvim\init.lua"

:: config neovide
:: ========================================

:: create neovide directory
if not exist "%APPDATA%\neovide" (
  mkdir "%APPDATA%\neovide"
)

:: generate config.toml
(
echo # this file is auto-generated by github.com/jwu/configs
echo include "%MY_ROOT_ESCAPED%\\common\\.config\\neovide\\config.toml"
) > "%APPDATA%\neovide\config.toml"

:: config omnisharp
:: ========================================

:: create omnisharp directory
if not exist "%USERPROFILE%\.omnisharp" (
  mkdir "%USERPROFILE%\.omnisharp"
)

:: copy omnisharp.json
copy /Y "%MY_ROOT%\common\.omnisharp\omnisharp.json" "%USERPROFILE%\.omnisharp\omnisharp.json"

:: config wezterm
:: ========================================

:: generate .wezterm.lua
(
echo -- this file is auto-generated by github.com/jwu/configs
echo local config = dofile^("%MY_ROOT_ESCAPED%\\common\\.wezterm.lua"^)
echo.
echo config.default_prog = { 'cmd.exe', '/s', '/k', '%MY_CONFIGS_ESCAPED%\\init.bat' }
echo.
echo return config
) > "%USERPROFILE%\.wezterm.lua"
